version: '3'

services:
  lettings_app:
    image: mrp0p/lettings:latest
    volumes:
      - static_volume:/app/static
    ports:
      - "9000:9000"
    environment:
      - DEBUG=False

volumes:
  static_volume:


