version: '3.8'
services:
  web:
    image: mrp0p/lettings:latest
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "9000:9000"

volumes:
  static_volume:
